services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: weassistant
      POSTGRES_PASSWORD: weassistant
      POSTGRES_DB: weassistant
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  qdrant_data:
